# Generated by Django 3.1.1 on 2023-01-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_display_on_main_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
    ]
